language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

#notifications:
#  slack: nukacode:HyFrc2QLi5PC5fPxadm07O5v
#  webhooks:
#      urls:
#        - https://webhooks.gitter.im/e/213257627c4e40ffc03c
#      on_success: change  # options: [always|never|change] default: always
#      on_failure: always  # options: [always|never|change] default: always
#      on_start: false     # default: false

matrix:
  fast_finish: true

before_script:
  - composer install

#script:
#  - phpunit --coverage-clover=coverage.clover
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload  --format=php-clover coverage.clover
